insert into todo(id, username, description, target_date, is_done) values(10001, 'prashant', 'Learn Angular JS', sysdate(), false)
insert into todo(id, username, description, target_date, is_done) values(10002, 'prashant', 'Learn Spring Boot', sysdate(), false)
insert into todo(id, username, description, target_date, is_done) values(10003, 'prashant', 'Learn ML', sysdate(), false)
insert into todo(id, username, description, target_date, is_done) values(10004, 'user', 'Learn XSHIT', sysdate(), false)
insert into todo(id, username, description, target_date, is_done) values(10005, 'user', 'Learn X', sysdate(), true)